# [START gae_python37_cloudsql_config]
runtime: python37

env_varibles:
    CLOUD_SQL_USERNAME: Daniel
    CLOUD_SQL_PASSWORD: Daniel4.0
    CLOUD_SQL_DATABASE_NAME: events
    CLOUD_SQL_CONNECTION_NAME: black-messenger-432018-s5:us-east4:testsqlinstance
# [END gae_python37_cloudsql_config]
